import type { ResearchNode } from './types';

// Every unlock has to change something the player can feel, not just a number.
export const RESEARCH: ResearchNode[] = [
  {
    id: 'ftth',
    name: 'FTTH Rollout',
    description: 'Fibre straight to the home. Raises the coverage ceiling and lifts residential speeds.',
    cost: 40000,
    points: 12,
    days: 12,
    requires: [],
    unlocks: ['+15% district coverage ceiling', 'Gigabit packages'],
    branch: 'fixed',
    tier: 1,
  },
  {
    id: 'gpon',
    name: 'GPON Splitters',
    description: 'Share one fibre across many homes. Access nodes get cheaper and serve more people.',
    cost: 65000,
    points: 20,
    days: 14,
    requires: ['ftth'],
    unlocks: ['-25% access node cost', '+20% access node capacity'],
    branch: 'fixed',
    tier: 2,
  },
  {
    id: 'fiber10g',
    name: '10G Fibre',
    description: 'Higher grade optics on every span you build from now on.',
    cost: 110000,
    points: 24,
    days: 18,
    requires: ['ftth'],
    unlocks: ['Fibre upgrades to tier 3', '+30% link capacity'],
    branch: 'fixed',
    tier: 2,
  },
  {
    id: 'backbone100g',
    name: '100G Backbone',
    description: 'Coherent optics across the core. The backbone stops being the bottleneck.',
    cost: 260000,
    points: 45,
    days: 26,
    requires: ['fiber10g'],
    unlocks: ['Core routers to tier 5', '-15% transit cost'],
    branch: 'fixed',
    tier: 3,
  },
  {
    id: 'metro_mesh',
    name: 'Metro Fibre Mesh',
    description: 'Dense coherent rings turn spare routes into a city-wide capacity fabric.',
    cost: 420000,
    points: 75,
    days: 30,
    requires: ['backbone100g'],
    unlocks: ['Fibre upgrades to tier 4', '+10% link capacity'],
    branch: 'fixed',
    tier: 4,
  },
  {
    id: 'noc',
    name: 'Network Operations Centre',
    description: 'A room full of screens and people who watch them. Faults get spotted before customers call.',
    cost: 55000,
    points: 10,
    days: 10,
    requires: [],
    unlocks: ['NOC panel', '-20% incident duration'],
    branch: 'ops',
    tier: 1,
  },
  {
    id: 'auto_dispatch',
    name: 'Automatic Dispatch',
    description: 'Technicians roll to faults on their own instead of waiting for your click.',
    cost: 90000,
    points: 22,
    days: 14,
    requires: ['noc'],
    unlocks: ['Auto-dispatch toggle'],
    branch: 'ops',
    tier: 2,
  },
  {
    id: 'ddos_scrub',
    name: 'DDoS Scrubbing',
    description: 'Wash hostile traffic before it reaches your core.',
    cost: 120000,
    points: 28,
    days: 16,
    requires: ['noc'],
    unlocks: ['DDoS impact halved'],
    branch: 'ops',
    tier: 2,
  },
  {
    id: 'sla_desk',
    name: 'Enterprise Service Desk',
    description: 'Dedicated account handling unlocks the contracts that actually pay.',
    cost: 140000,
    points: 35,
    days: 18,
    requires: ['noc'],
    unlocks: ['Enterprise contracts', 'Higher contract volume'],
    branch: 'ops',
    tier: 3,
  },
  {
    id: 'predictive_maintenance',
    name: 'Predictive Maintenance',
    description: 'Telemetry schedules service before heat, optics and power systems become incidents.',
    cost: 360000,
    points: 70,
    days: 28,
    requires: ['auto_dispatch', 'ddos_scrub'],
    unlocks: ['Failure risk forecast', 'Automatic overnight scheduling', '-20% network maintenance'],
    branch: 'ops',
    tier: 4,
  },
  {
    id: 'edge_compute',
    name: 'Edge Computing',
    description: 'Cache and compute close to the customer. Cuts what you pay upstream.',
    cost: 320000,
    points: 60,
    days: 28,
    requires: ['backbone100g'],
    unlocks: ['Data centres', '-30% transit cost'],
    branch: 'fixed',
    tier: 4,
  },
  {
    id: 'mobile_4g',
    name: '4G LTE',
    description: 'Take the network mobile. Towers cover whole neighbourhoods at once.',
    cost: 300000,
    points: 55,
    days: 30,
    requires: ['fiber10g'],
    unlocks: ['Mobile towers', 'Mobile packages'],
    branch: 'mobile',
    tier: 3,
  },
  {
    id: 'mobile_5g',
    name: '5G Standalone',
    description: 'A cloud-native mobile core. Denser capacity and business-grade mobile services.',
    cost: 750000,
    points: 100,
    days: 40,
    requires: ['mobile_4g', 'backbone100g'],
    unlocks: ['Tower tier 4', 'Network slicing', '+35% mobile revenue'],
    branch: 'mobile',
    tier: 4,
  },
  {
    id: 'private_5g',
    name: 'Private 5G Slices',
    description: 'Reserved radio and fibre capacity creates premium low-latency enterprise services.',
    cost: 980000,
    points: 135,
    days: 48,
    requires: ['mobile_5g', 'sla_desk'],
    unlocks: ['+20% value on new contracts', '+1 simultaneous contract offer'],
    branch: 'mobile',
    tier: 5,
  },
  {
    id: 'ai_ops',
    name: 'AI Network Optimisation',
    description: 'The network reroutes and rebalances itself while you look at the map.',
    cost: 900000,
    points: 120,
    days: 45,
    requires: ['edge_compute', 'auto_dispatch'],
    unlocks: ['Auto capacity balancing', '-25% packet loss impact'],
    branch: 'ops',
    tier: 5,
  },
];

export const researchById = (id: string) => RESEARCH.find((r) => r.id === id);

export function isAvailable(node: ResearchNode, done: string[]) {
  return node.requires.every((r) => done.includes(r));
}

export function researchModifiers(done: string[]) {
  return {
    coverageCeiling: 0.75 + (done.includes('ftth') ? 0.15 : 0) + (done.includes('gpon') ? 0.1 : 0),
    accessCostMul: done.includes('gpon') ? 0.75 : 1,
    accessCapacityMul: done.includes('gpon') ? 1.2 : 1,
    linkCapacityMul: (done.includes('fiber10g') ? 1.3 : 1) * (done.includes('metro_mesh') ? 1.1 : 1),
    maxLinkTier: done.includes('metro_mesh') ? 4 : done.includes('fiber10g') ? 3 : 2,
    maxCoreTier: done.includes('backbone100g') ? 5 : 3,
    maxTowerTier: done.includes('mobile_5g') ? 4 : 2,
    transitCostMul: (done.includes('backbone100g') ? 0.85 : 1) * (done.includes('edge_compute') ? 0.7 : 1),
    incidentDurationMul: done.includes('noc') ? 0.8 : 1,
    incidentRateMul:
      (done.includes('noc') ? 0.85 : 1) *
      (done.includes('predictive_maintenance') ? 0.85 : 1) *
      (done.includes('ai_ops') ? 0.75 : 1),
    maintenanceCostMul: done.includes('predictive_maintenance') ? 0.8 : 1,
    hasMaintenanceForecast: done.includes('predictive_maintenance'),
    ddosMul: done.includes('ddos_scrub') ? 0.5 : 1,
    lossImpactMul: done.includes('ai_ops') ? 0.75 : 1,
    mobileRevenueMul: done.includes('mobile_5g') ? 1.35 : 1,
    contractRevenueMul: done.includes('private_5g') ? 1.2 : 1,
    hasNoc: done.includes('noc'),
    hasAutoDispatch: done.includes('auto_dispatch'),
    hasEnterprise: done.includes('sla_desk'),
    hasMobile: done.includes('mobile_4g'),
    hasPrivate5g: done.includes('private_5g'),
    hasAutoBalance: done.includes('ai_ops'),
  };
}

export type ResearchMods = ReturnType<typeof researchModifiers>;
